CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS tokens (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    symbol VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    decimals INTEGER NOT NULL,
    logo VARCHAR(255) NOT NULL,
    slug VARCHAR(100) NOT NULL,
    blockchain_id BIGINT NOT NULL REFERENCES blockchains(chain_id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
